### ISSUE TITLE
How to search for multiple tags?

### ISSUE THREAD

**Issue by nick-s-b** [vasanthv/webtag#14]
Hi all,
Webtag has been my bookmarking system for months and I love it. It's cleaned up my browser tabs.
I have a retrieval question: how does one find intersection of two tags? For example, I'd like to return all links that have both the "#french" and "#cooking" tags. If I type "#french #cooking" I get returned all tags that have either of these terms.  But I'd like only those that have both...
Thanks!

**Comment by vasanthv** [comment]
Hi Nick, currently Webtag support only OR queries. But this is a really good feature request. Let me look into it and update here when it is available. Thanks for bringing this up.

**Comment by nick-s-b** [comment]
@vasanthv Thank you. And if you think about it, this is how most searches work... if you type "french cooking" into Google, you'd expect results where both words occur and not a mix of pages on "cooking" and "french", for example.

**Comment by vasanthv** [comment]
@nick-s-b Yes that was right. This commit should fix this https://github.com/vasanthv/webtag/commit/db60c4a04eb9ce04d53429f55a125e2c95c0d356 and it is deployed right now. Hope it is helpful. Thanks for reaching out and keep using the app and let me know in what ways I can improve the app.
