### ISSUE TITLE
Feature Request: ActivityPub Support

### ISSUE THREAD

**Issue by aadityabhatia** [vasanthv/webtag#6]
First off, excellent job with keeping the project simple with plain text content. Love the ability to tag other people for social bookmarking!

I can imagine that a lot of people / communities would want to run their own instance of webtag (myself included) and share with others both within and beyond the ecosystem. Integration / federation through [ActivityPub](https://w3c.github.io/activitypub/) or similar protocol would expand reach into the fediverse.

**Comment by vasanthv** [comment]
Webtag is meant to be a simple bookmarking service and ActivityPub support is not in radar for it.
