### ISSUE TITLE
Bookmarklet doesn't work with uBlock Origin enabled

### ISSUE THREAD

**Issue by nick-s-b** [vasanthv/webtag#7]
Hi,

I've noticed that the bookmarklet fails to load the fields most of the time and it only works when I disable uBO. I use Chrome browser.
Console shows this error:

```
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src http: https:".
```

Anyone know how to fix this? Thanks so much!

**Comment by vasanthv** [comment]
Bookmarklet is a piece of javascript code that runs on the browser, if uBlock is blocking it from executing, I don't think we can find a way to make it work until you unblock the feature. Let me know if you find other bookmarklets working and just Webtag bookmarklet is not working.
